version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Docker-Blog/Dockerfile
    # Removed port mapping to prevent direct access to 127.0.0.1:8000
    # ports:
    #   - "8000:8000"
    volumes:
      - ./Volume-Blog:/app
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:piter@pg:5432/blog
    networks:
      - app-network

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: piter
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - ./Volume-Database:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: piter271006@gmail.com
      PGADMIN_DEFAULT_PASSWORD: piter
    ports:
      - "8080:80"
    depends_on:
      - pg
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 for NGINX
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
